// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puhirbzkpxnsnazdjfhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1aGlyYnprcHhuc25hemRqZmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDc4NjMsImV4cCI6MjA2NjYyMzg2M30.kU14mSlEXpgQ5PBcRJEoGCeq2ZLKHxrod_ZMGkEaAXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});